### ISSUE TITLE
Issue with BankAccountNumber.TryParse for 'Marginalen Bank' Accounts

### ISSUE THREAD

**Issue by DanJoh74** [jellyhive/SwedishBankAccounts#10]
I've encountered an issue while validating account numbers for "Marginalen Bank". When attempting to parse account numbers with `BankAccountNumber.TryParse` using `InitOptions.Strict`, the method returns `false` for valid "Marginalen Bank" account numbers.

### Possible Solution:
Changing from `BankAccountNumberType1B` to `BankAccountNumberType1A` for "Marginalen Bank" seems to solve the issue.

**Comment by jonaswikstrom** [comment]
Hello Dan,

This is probably a typo. In the documentation https://www.bankgirot.se/globalassets/dokument/anvandarmanualer/bankernaskontonummeruppbyggnad_anvandarmanual_sv.pdf, the "Multitude Bank," which has the same format as "Marginalen Bank," uses `BankAccountNumberType1A`. A fix will come during the day.
